### ISSUE TITLE
Service Provider metadata - store in DB instead of using config files?

### ISSUE THREAD

**Issue by stodge** [OTA-Insight/djangosaml2idp#12]
I'm not actually using this project - more I'm investigating options - but I have what is probably a naive question.

Your documentation says you have to provide configuration for every Service Provider in a Python dictionary. Would it make more sense to store this metadata using a Django model in the DB so this process is dynamic? Or is that a design decision that can't easily be modified?

Thanks

**Comment by mhindery** [comment]
Hi @stodge . There is nothing inherently impossible about storing some config in models. Some remarks on that:
- I work with pysaml2 to do the actual saml2 processing, and it requires the config in a specific format. This includes the metadata (with an entry for each SP) as xml file on the filesystem. If you want to make it dynamic, I'd image you'd need to rewrite that file upon changes in your SP model instances and reload the config. It also has the possibility to fetch metadata from a url instead of local filesystem, but that requires an additional endpoint for you to write. This would seem like the biggest hurdle to make the config more dynamic.
- Adding models means also adding migrations and they add more complexity to setup, writing an admin ... Having no models and a more 'stateless' code means less to think about when developing the code (less legacy to support and migrate). Due to the migrations that come with models and additional complexity, they seem not worth the added value of a more dynamic configuration in most cases, as most users would have a rather static set of SP's to interact with. 
- I've started djangosaml2idp having worked before with djangosaml2, and have therefore used the similar approach of using the config dict in the settings. Having the same 'architecture' in both pysaml2 / djangosaml2 / djangosaml2idp which are all related is an advantage as it makes it easier to pick up and get started.

So that is why I don't use models. That being said, it should certainly be possible to move some things to a model in the db if your use-case requires it. I would need some convincing to add it to the main release here though :)
