### ISSUE TITLE
Interested in a PR?

### ISSUE THREAD

**Issue by lgarvey** [OTA-Insight/djangosaml2idp#17]
Hi,

I've forked your repo and made a few amends including some changes to make the module more extensible. I'm also building a set of tests.

https://github.com/lgarvey/djangosaml2idp

I'm wondering if you'd be interested in reviewing, and potentially merging these?  If so I'll raise a PR.

Cheers,
Lyndon

**Comment by lgarvey** [comment]
Hi, 

Sounds good! 

I needed to add support for get-bindings to integrate with Google Identity. Some other amends to the processors were required to support an AWS IAM Saml integration. So I assume they'd benefit future users.

The module is being used on a UK government SSO project: https://github.com/uktrade/staff-sso/pull/177

Happy to spend time contributing to this project.

There's a bit more I'd like to do - mainly fleshing out the tests, but I'll raise a PR for you to review.

**Comment by mhindery** [comment]
Hi @lgarvey , I saw the PR on the uktrade repo was merged recently. Do you still plan on putting some changes into a PR to merge in this repo as well? I'm asking because this PR https://github.com/OTA-Insight/djangosaml2idp/pull/19 seems to be looking into adding stuff that your fork also added (the redirect binding and customizable user identifier attribute). If both of you are implementing the same functionality, it's a bit of a wasted effort which is better spent elsewhere, so perhaps it's not necessary for @askvortsov1 to look into this further if it's already implemented and "near-mergeable"?

**Comment by lgarvey** [comment]
Hi,

I was caught up with the uktrade amends, but plan to spend tomorrow
finishing off what I started with this codebase. I'll raise a PR now, but
want to add some more tests before it is merged.

L
