### ISSUE TITLE
[Additional Features] Attribute policies, attribute rewrite, agreement screen

### ISSUE THREAD

**Issue by peppelinux** [OTA-Insight/djangosaml2idp#22]
Hi, first of all thank you very much for having merged my contributions.
I'd like to discuss with your help some of [following notes](https://github.com/peppelinux/Django-Identity/blob/master/README.md#django-saml-idp-doesnt-filter-out-attribute-policy-restrictions):

- attribute filter/policies: [actually found in official pySAML2 docs](https://pysaml2.readthedocs.io/en/latest/howto/config.html#policy)!;
- possibility to  dinamically rewrite or create additional attributes before relasing them to SP;
- user agreement screen, to inform users about the attributes that are going to be released to the SP;

I agree that attribute transformation and rewrite should be delegated to pySAML2, so I opended this [feature request](https://github.com/IdentityPython/pysaml2/issues/587). Therefore the agreement screen could be a good topic to discuss on.

**Comment by askvortsov1** [comment]
I'm a contributor not a maintainer, and I'm somewhat new to this, so please take all this with a grain of salt.

For points 1 and 2, I feel it might be easiest to customize this through processors for each individual use case. As you mentioned, attribute rewriting would probably be better implemented on the pySAML2 level. I'll be sure to take a look there if I have time. 

I have a few questions about the user agreement screen idea. I'm assuming you would only want to show it to each user on the 1st time they agree (otherwise would be an annoyance, sort of defeating the whole purpose of hassle-free SSO login). Because we can't count on permanent cookies / cookies at all, we'd have to store data about this. Here's an implementation proposal:

We add an intermediate view in between login and data being sent to the SP. The user is then shown all attributes being sent to the SP, as well as the maximal amount of information about the SP available to the IDP. The user can then de-select any attributes they don't want to be sent. By default, they will only be shown this screen once, but they can choose to be shown it every time. We can then store all this in the database. This user-agreement screen could be enabled or disabled per SP in config.

Thoughts?

**Comment by peppelinux** [comment]
I agree,
We could set default expiration time in settings.py, once the previous agreement stored in db is expired the agreement screen Will Be show again to the user.

In the agreement screen we Will show attributes names and values and a customizable agreement message.

There could Be the possibility to implement, also, a checkbox in the login form. This could force the expiration of the last agreement.

The possibility to let the user to exclude some attributes to being passed to an SP Is awesome!

**Comment by peppelinux** [comment]
I realized that the place to implement the attribute rewrite is in Processors, an example is create_identity:
https://github.com/OTA-Insight/djangosaml2idp/blob/master/djangosaml2idp/processors.py#L22

**Comment by peppelinux** [comment]
login/agreement could Be the url, accepting GET for agreement form and POST for submission. The submission should save that accounting profile of the user related to that SP , then render the Page for post/redirect the encoded auth response in base64 to the SP

**Comment by peppelinux** [comment]
Talking with collegues from my federation I realize that:

- agreement could Be given only to optional attributes, all the isRequired from sp should not be excluded, this would be a soluzione to avoid problems to sp that are not so much well configured
- I think to add an Accounting model in models.py to manage users nameID (persistentID, transienti, email...) and with related agreements
- what do you think about a single checkbox with label "renew my agreement" or "forget my last agreement" or... Any ideas?

**Comment by askvortsov1** [comment]
So a few thoughts.

First of all, we could make this feature much simpler if we didn't have the ability to select individual attributes. This way, we wouldn't be forced to awkwardly shove in a chain of redirects in the middle of the Login Process view. It would also be a simpler experience for the user, and we wouldn't compromise integrity of any SPs that depend on certain attributes. To be honest, considering that SAML based authentication is generally more often used to connect services within an organization than to act as authentication for outside apps (like OAuth), such a feature would be very rarely used. A simple informational opt-in would be better.

I agree about a model with attributes being a foreign key to the User model and a CharField recording the entity ID. One question: should we store the attributes that the User has agreed to share? This way, we could reprompt the User if more attributes are requested in the future.

For the frontend, I think we need to show the user info about the requesting SP (entity ID, for example), as well as a mapping of all information that will be sent to the SP. On that note, do we want to expand the SP Config section to allow IdP coordinators to add a human-readable name and description for each SP to me shown instead of the entity id?

I think we need a button saying "I agree" that would send the User (and the SAMLResponse) onto the SP, a button saying "I Disagree" that would return them back to the homepage. For the "agree" button, there should be a checkbox saying "Don't ask me again". If this is selected, a record will be stored in the DB, and they won't be shown the screen again (unless we decide to show the screen when the attribute mapping changes).

That being said, if we go with this model, I'll probably be able to get this done later today. If so, I'll set up a PR in my branch and open it up to your comments @peppelinux so that we can confirm that it fits your vision of what we want.

**Comment by peppelinux** [comment]
Great answer @askvortsov1, very fun. I reply as follow

> This way, we wouldn't be forced to awkwardly shove in a chain of redirects in the middle of the Login Process view. It would also be a simpler experience for the user, and we wouldn't compromise integrity of any SPs that depend on certain attributes. 

That's my same thought, otherways I know that shibboleth idp permits that kind of granularity in the agreement form. Agreement with single ones could be done in a single submit, if its a single or multiple fields doesn't matter. I'd fill better if we code the form with singles attributes (but hidden, for example). We could store in the Accounting schema an hash of the agreement dictionary.... 

> One question: should we store the attributes that the User has agreed to share? This way, we could reprompt the User if more attributes are requested in the future.

...If an attribute will change the hash for that user/sp will change and the Agreement screen must be submitted again. If in the login form the user will select "renew/forget-previous general agreement" the result will be the same of previous.

> For the frontend, I think we need to show the user info about the requesting SP (entity ID, for example), as well as a mapping of all information that will be sent to the SP. On that note, do we want to expand the SP Config section to allow IdP coordinators to add a human-readable name and description for each SP to me shown instead of the entity id?

I think that the entity ID is the only uniformed value, regarding additional options I would like to implement well know behaviours from the working federation contexts. Information should be taken from metadata, even if it's very rare to view some more eloquent metadata, even if they can be more... Fill free to explain and suggest any alternative, I'm very curious :)

> For the "agree" button, there should be a checkbox saying "Don't ask me again". If this is selected, a record will be stored in the DB, and they won't be shown the screen again (unless we decide to show the screen when the attribute mapping changes).

I think that the default behviour should be the "don't ask me again" profile you mentioned, by default, once an agreement is submitted it will be holded by the IDP. To renew agreement I think to implement a single checkbox, in the login form, as previously explained. Your idea are also good, so fill free to bring here all the elements you think are important.

> That being said, if we go with this model, I'll probably be able to get this done later today. If so, I'll set up a PR in my branch and open it up to your comments @peppelinux so that we can confirm that it fits your vision of what we want.

You're a sniper Alexander and a very fast hand, I know. So I'll put here additional ideas to get developed before the comments:

- The Persistend ID encoding algortihm should be copied by shibboleth idp 3. This way we'll permit to migrate easily from shibboleth to djangosaml2idp
- We should decide which fields to put in the Accounting schema, something like:
  - User_id as fk to user
  - user_nameid (related to the user)
  - sp_nameid (related to sp)
  - agreement_hash (we cannot se which attributes but only the hash of the key:value dict)
  - create_date
  - modified_date

user_id, user_nameid and sp_nameid should be unique_together.
An eye on shibboleth behaviour should also be better for major improvements.

great job

**Comment by askvortsov1** [comment]
> That's my same thought, otherways I know that shibboleth idp permits that kind of granularity in the agreement form. Agreement with single or multiple ones could be done in a single submit. I'd fill better if we code the form with singles attributes checkboxes (but hidden, for example). We could store in the Accounting schema an hash of the agreement dictionary as It comes from submission.

As I mentioned in my previous post, I have 2 main concerns about allowing granular control:
1. Implementation would be convoluted, because it would have to interrupt the LoginProcessView after determining the SP and attr dictionary, but before generating a SAMLResponse. This redirect loop would have a lot of possible points of failure.
2. Unlike OAuth, SAML is generally used within internal systems. As such, which attributes are being exchanged are a decision of the company running both systems. This applies equally to this repo: there isn't an API for unsolicited SPs: everything has to be manually coded in. Allowing users to interfere with individual attributes being transferred could cause a lot of problems, with minimal benefit (if any).

> ...If an attribute will change the hash for that user/sp will change and the Agreement screen must be submitted again. If in the login form the user will select "renew/forget-previous general agreement" the result will be the same of previous.

I would be opposed to storing a dictionary of values (hashed or unhashed), because there is no reason to reprompt the user if the value of a given attribute changes. I would prefer to store just the attribute names in a comma-delimited string, which we could then hash if appropriate.

> I think that the entity ID is the only uniformed value, regarding additional options I would like to implement well know behaviours from the working federation contexts. Information should be taken from metadata, even if it's very rare to view some more eloquent metadata, even if they can be more... Fill free to explain and suggest any alternative, I'm very curious :)

The system woudn't work without the entity ID, so we can safely assume we have that. Trying to extract information from the metadata is possible, but I think that would be less convenient for system admins than my proposal. Essentially:

`SAML_IDP_SPCONFIG = {
    'test_generic_sp': {
        'processor': 'djangosaml2idp.processors.BaseProcessor',
        'attribute_mapping': {},
        # Other stuff as needed
        'displayed_name: 'Generic SP',
        'displayed_description': 'Generic SP Description'
    }
}`

> I think that the default behviour should be the "don't ask me again" profile you mentioned, by default, once an agreement is submitted it will be holded by the IDP. To renew agreement I think to implement a single checkbox, in the login form, as previously explained. Your idea are also good, so fill free to bring here all the elements you think are important.

I would be highly against trying to put something into the login form. The current system relies on a LoginRequiredMixin, which in my opinion is a really good design idea because it maximizes customizability of the implementation. I would propose going with my idea, but we can have the "don't show this again" box checked by default to minimize annoyance for users.

> * in SLO I pushed some code refactor, probably I would not did them but now to avoid conflicts wouldn't it be Better to merge SLO commits in master branch OR start a new branch from SLO? What do you preferabout this, if you think this important

I'll wait for your PR before implementing this, so that we can get the best of both world.

> * The Persistend ID encoding algortihm should be copied from shibboleth idp 3. This way we'll permit to migrate easily from shibboleth to djangosaml2idp

I'm a bit confused what we need this for?

> * We should decide which fields to put in the Accounting schema, something like:
>   
>   * User_id as fk to user
>   * user_nameid (related to the user)
>   * sp_nameid (related to sp)
>   * agreement_hash (we cannot se which attributes but only the hash of the key:value dict)
>   * create_date
>   * modified_date
> 
> user_id, user_nameid and sp_nameid should be also unique_together.

I don't see the need for storing user_nameid, or any dates in the accounting model. Also, as I mentioned above, I think a comma separated string of attr names would work better than a dict (which we can then hash)

**Comment by askvortsov1** [comment]
@peppelinux I've coded up an implementation of this, and made it a PR here: https://github.com/askvortsov1/djangosaml2idp/pull/4. Please let me know what you think.

**Comment by peppelinux** [comment]
PersistentID and TransientId or whatever nameId that identify a user in Saml2 context should be LinkedIn to user's accounting data. Some sp use the user nameID instead of other attributes, so a custom attribute processor should also deal with this. You can push your commit as a base, then Will follow my contributions on this. I'll explain Better these features, do not worry.

Shibboleth idp login form come with two checkboxes: stay logged and forget my preferences.
I Need a create and modify datetime to deal with expiration features. The preferences should be flushed After a predefined time we put in Settings.py

The checkbox should be unchecked by default ro leave the decision to the users to flush their past agreements.

I pruposed an hash because of One of the attributes Will change It's value the agreement could expire. This Is not mandatory, i can consider your idea of a comma separate field list. We'll see, great job

**Comment by askvortsov1** [comment]
> PersistentID and TransientId or whatever nameId that identify a user in Saml2 context should be LinkedIn to user's accounting data. Some sp use the user nameID instead of other attributes, so a custom attribute processor should also deal with this. You can push your commit as a base, then Will follow my contributions on this. I'll explain Better these features, do not worry.

What I'm saying is that my proposed solution ForeignKeys to the User model. Irregardless of what the SP wants as a NameID, the User model instance will always be the same for a given user, so there's no need to collect and store the NameID or PersistentID or etc.

> Shibboleth idp login form come with two checkboxes: stay logged and forget my preferences.

As I mentioned before, djangosaml2idp is completely agnostic as to login implementation. This means that we CANNOT modify the login form. I added in a forget my preferences button in https://github.com/askvortsov1/djangosaml2idp/pull/4, "Stay logged in" is up to the login system that each site chooses.

> I Need a create and modify datetime to deal with expiration features. The preferences should be flushed After a predefined time we put in Settings.py

Point taken about the need to log creation datetime so that we can put an optional expiry feature. I'll make this change and commit to my open PR

> The checkbox should be unchecked by default ro leave the decision to the users to flush their past agreements.

Similarly agreed. I'll make the relevant adjustments to my open PR.

> I pruposed an hash because of one of the attributes Will change Its value the agreement could expire. 

I'm against storing the attribute values, because then any change in any attr value will reprompt the user. This could easily become a nuisance.

Likewise, I'd prefer to go with unhashed attribute names because then we could reprompt the user only if new attributes are added. If an attribute that was sent before is no longer being sent, there is no need to reprompt the user.

**Comment by askvortsov1** [comment]
@peppelinux I've made these changes in https://github.com/askvortsov1/djangosaml2idp/pull/4

**Comment by peppelinux** [comment]
I agree about PersistentID and other nameID, I will do a better reconnaissance about where to put and manage these SAML specifications for managing sessions. Actually a fk to user_id is good enough.

Ok the "forget my preferences" button, I'll testing it today.

Implementation of creation and modify datetime are welcome, thank you.

Ok about the unhashed attr as a sorted list coded to comma separated value, we need to compare the result so if we do not have an hash we should move to this kind of format if you agree.

I moving into tests :+1:

**Comment by peppelinux** [comment]
Ok I'm closing it and open a new Issues specifically related to user agreement. 
https://github.com/OTA-Insight/djangosaml2idp/issues/31
