### ISSUE TITLE
[CONTRIBUTING] pep8 code style

### ISSUE THREAD

**Issue by peppelinux** [OTA-Insight/djangosaml2idp#26]
I'm moving to implement Agreement screen and SLO and a contributor told me that we should not use pep8 style in the code, thread here: https://github.com/askvortsov1/djangosaml2idp/pull/1#issuecomment-473718057

Should we put this information in CONTRIBUTING.md or should we instead move to a pep8 compliance?

I apologize I'd prefer the second one :)

**Comment by askvortsov1** [comment]
In my personal opinion, 80 chars is a bit arbitrary, although there are probably some code sections that could be made clearer/simpler/more readable if we split them up. The line at the start of build_authn_response in views.py comes to mind.

**Comment by peppelinux** [comment]
I agree about a soft pep8 compliance, not too much arbitrary but funcional. I think that this would also facilitate other contributions, in users that coding style matters.

We probably would wait for Mathieu point of view, before starting these minor adjustments

**Comment by mhindery** [comment]
The code style guide is described in the current contributing.md document. It's pep8 with some exceptions allowed such as the infamous 80-char limit which I find arbitrary and outdated. I prefer readability instead of enforcing this arbitrary rule, and this is one which I find contraproductive. Some other exceptions are related to indentation, as there I also have found that strict enforcement can lead to worse readability. Then there's a missing docstring exception which is allowed, bare except, something lambda-functions related, and I think that's about it. If you think one shouldn't be allowed for a good reason, I'm happy to reconsider, these are the rulesets we use at work for our projects and it's something that works for us, but as this is a far smaller codebase, it might be more strict? Only the line limit I'm really against enforcing.
