### ISSUE TITLE
Add option not to use error handler

### ISSUE THREAD

**Issue by askvortsov1** [OTA-Insight/djangosaml2idp#58]
Sometimes, it might be better to let exceptions reach Django so that the debugging system can be used. A setting should added for whether to use djangosaml2idp's error handling system

**Comment by askvortsov1** [comment]
Addresssed in #59

**Comment by mhindery** [comment]
I don't think this warrants an additional setting, because it's already possible to achieve this by subclassing the views, which is the reason for implementing this as a separate method. Now that I look at it, it is annoying that you need to subclass multiple views though, so I think it would be better if the error handler method isn't a method on the mixin, but a standalone function. The logging of the error could also be moved to the error_view, which you can also override already, and then you could choose there to not log the error and deal with it in your own way. I'll have a look at it. I'm more in favor of constructing the code to allow extending behaviour this way, especially if it's likely to be custom for everybody's case, rather than add some toggles via additional settings. Does that make sense?

**Comment by askvortsov1** [comment]
That would also make sense. One change I would keep though is requiring an exception parameter for handle_error

**Comment by mhindery** [comment]
I've made some code changes which I think allows you to achieve all this in the linked MR. Could you have a look if this works for you and if you are missing something @askvortsov1 ? Thanks!

**Comment by askvortsov1** [comment]
Looks great! I'll close this issue and my PR.
